### ISSUE TITLE
Multiple file end with option

### ISSUE THREAD

**Issue by ashitabh** [madhanir/databricks_filesystem#2]
How do I pass multiple values for file_end_with

For example,I want both csv and json in list

**Comment by madhanir** [comment]
Hi @ashitabh, 

Thanks for submitting the feature request! The requested feature is now available in the latest version v0.0.4. Please test and explore it. 

I would appreciate your feedback and, if you're satisfied, a star ⭐ for this project.

Regards,
Rahul Madhani
